### ISSUE TITLE
Payment Initiation model version 3.1.4 missed fields (Refund)

### ISSUE THREAD

**Issue by jsanhc** [OpenBankingToolkit/openbanking-toolkit#16]
### Description
It has been detected that the objects generated from swagger file version 3.1.4 (payment initiation) was wrong and the object `Refund` doesn't exist defined in the generated model when was generated at 2020-05-19.

- The OBIE spec was wrong defined and miss fields, will be necessary generate again the model to fix the missed fields.

### swagger file correction
[v3.1.4 Payment initiation swagger file](https://raw.githubusercontent.com/OpenBankingUK/read-write-api-specs/v3.1.4/dist/swagger/payment-initiation-swagger.json)

### tasks
- [x] Generate the model with the correct payment initiation swagger file
- [x] Compare the model generated with the current model on [openbanking-uk-datamodel](https://github.com/OpenBankingToolkit/openbanking-uk-datamodel) to detect issues or fields missed.
- [x] Overwrite the model on [openbanking-uk-datamodel](https://github.com/OpenBankingToolkit/openbanking-uk-datamodel)

**Comment by jsanhc** [comment]
### Command used to generate the model

```bash
java -jar ../../swagger-codegen-cli-2.4.17.jar generate \
-i https://raw.githubusercontent.com/OpenBankingUK/read-write-api-specs/v3.1.4/dist/swagger/payment-initiation-swagger.json \
-DuseBeanValidation=true \
-Dmodels \
--model-package uk.org.openbanking.datamodel.payment \
--group-id com.forgerock.openbanking \
--artifact-id openbanking-sdk \
-l java \
--library resttemplate \
-o generated
```
### Swagger file used
- [v3.1.4 payment-initiation-swagger.json](https://raw.githubusercontent.com/OpenBankingUK/read-write-api-specs/v3.1.4/dist/swagger/payment-initiation-swagger.json)

**Comment by jsanhc** [comment]
### Changes in [openbanking-uk-datamodel](https://github.com/OpenBankingToolkit/openbanking-uk-datamodel)
- uk.org.openbanking.datamodel.payment
#### OBWriteDomesticStandingOrder3
- `OBWriteDataDomesticStandingOrder3` to `OBWriteDomesticStandingOrder3Data`

#### OBWriteInternationalResponse4Data
- Added refund property `OBWriteInternationalResponse4DataRefund`
- `OBWriteInternationalResponse4DataRefund`: new class
- `OBWriteInternationalResponse4DataRefundAgent`: new class
- `OBWriteInternationalResponse4DataRefundCreditor`: new class
  
#### OBWriteInternationalScheduledResponse5Data
- `OBWriteInternationalRefundResponse1DataRefund` changed to `OBWriteInternationalResponse4DataRefund`

#### OBWriteInternationalStandingOrderResponse6Data
- `OBWriteInternationalRefundResponse1DataRefund` changed to `OBWriteInternationalResponse4DataRefund`
