### ISSUE TITLE
Datatype Error in field OBRisk#CountrySubDivision version 3.1.6

### ISSUE THREAD

**Issue by jsanhc** [OpenBankingToolkit/openbanking-toolkit#27]
# Description
**Version**: 4.1.6

**Ticket description**: `Post consent failure - 400 Error returned`
```shell
"Message": "Malformed JSON request. Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token\n at [Source: (PushbackInputStream); line: 1, column: 773] (through reference chain: uk.org.openbanking.datamodel.payment.OBWriteDomesticConsent4[\"Risk\"]->uk.org.openbanking.datamodel.payment.OBRisk1[\"DeliveryAddress\"]->uk.org.openbanking.datamodel.payment.OBRisk1DeliveryAddress[\"CountrySubDivision\"])",
```

- The field `CountrySubDivision` is defined like String in the swagger file [version 3.1.6](https://github.com/OpenBankingUK/read-write-api-specs/blob/v3.1.6/dist/swagger/payment-initiation-swagger.json) but in the current implementation version 3.1.6 is defined like as List and stored like a Array, it must necessary upgrade the datatype of `countrySubDivision` to String.
- OB applied the fix [fixed CountrySubDivision string](https://github.com/OpenBankingUK/read-write-api-specs/commit/406d003288d0aaadf63d15b22fda00d747751a79) **committed on 27 May 2020** after release the version `3.1.5` but they applied the fix for all old 3.x.x versions without create a new object, it means that we need upgrade all objects creating a breaking change.

**Comment by jsanhc** [comment]
# Tasks
- [x] Generate the source from [payment initiation swagger file v3.1.6](https://github.com/OpenBankingUK/read-write-api-specs/blob/v3.1.6/dist/swagger/payment-initiation-swagger.json) to update [uk-datamodel](https://github.com/OpenBankingToolkit/openbanking-uk-datamodel)
- [x] Create a data base upgrade to upgrade the `countrySubDivision` datatype from Array to String
> To run the upgrade will be necessary, in configuration, set to `true` the below value:
```yaml
  # Switch for migrating the FR document classes within MongoDB
  # See https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/279
  mongo-migration:
    enabled: true
```
- [x] Update functional tests
- [x] Update postman collections

**Comment by jsanhc** [comment]
Solved.
