### ISSUE TITLE
Variable Recurring Payments (VRPs) for v3.1.8

### ISSUE THREAD

**Issue by matt-wills** [OpenBankingToolkit/openbanking-toolkit#36]
## Story

As a customer of the OB Toolkit
I want to be able to use VRPs
so that I can be sure I am compliant with the latest OB specifications.

## Acceptance criteria

- v3.1.8 of VRPs is supported.
- I can see the required v3.1.8 VRP URLs in the Discovery API.

## Tasks

- [x] Analyse functional changes in spec and present list of issues to implement
- [x] _1 Day_ Generate new uk-datamodel classes. - See #45
- [x] _2 Days_ Generate new controller classes/interfaces with relevant changes. See #45
- [x] _3 Days_ Add new functional tests
- [x] _1 Day_ Create Postman tests
- [x] _3 Days_ #46
- [x] _3 Days_ #47
- [x] _3 Days_ #48
- [x] _1 Day_ Update config files (e.g. RS discovery config - `application.yml` - with active/inactive API versions).
- [x] _2 Days_ Create new VRP Consent UIs - See #43 
- [x] Create new VRP Consent Revocation Dashboard - See #42 
- [x] Create Bank VRP revocation pages #44
- [x] _1 Day_ Check discovery endpoint - allow enable/disable in spring config
- [ ] **PENDING**: Control parameters - validation - see #50

Estimate 14 days effort. Say 17 man days of effort with a bit of wriggle room.

### Release Notes

Affected Apps:
* openbanking-aspsp
* openbanking-reference-implementation

**Comment by BohoCode** [comment]
Create Variable Recurring Payments Consent Revocation Dashboard

VRP allows PSUs to Revoke existing VRP agreements via the TPP application. 
https://standards.openbanking.org.uk/customer-experience-guidelines/pis-core-journeys/vrp/vrp-consent-dashboard-revocation/v3-1-8/

**Comment by BohoCode** [comment]
Create a VRP consent page

Variable Recurring Payments requires new constent pages. 
Set up a basic VRP;
https://standards.openbanking.org.uk/customer-experience-guidelines/pis-core-journeys/vrp/vrp-payments-with-an-sca-exemption/v3-1-8/
Set up Sweeping;
https://standards.openbanking.org.uk/customer-experience-guidelines/pis-core-journeys/vrp/vrp-payments-under-sweeping-access/v3-1-8/
With a delegated Strong Customer Auth (is this needed?)
https://standards.openbanking.org.uk/customer-experience-guidelines/pis-core-journeys/vrp-payments-with-delegated-sca/v3-1-8/

**Comment by BohoCode** [comment]
Create Bank VRP revocation pages

In the VRP specifications and Guidelines the ASPSP must support a flow that allows the PSU to authorize with the bank and then review all VRP consents and revoke them. 
https://standards.openbanking.org.uk/customer-experience-guidelines/pis-core-journeys/vrp/vrp-access-dashboard-revocation/v3-1-8/

**Comment by BohoCode** [comment]
@jorgesanchezperez and I have decided that we don't need to implement the VRP dashboard for a TPP. We also don't need to support the pages that allow a PSU to use the bank pages to revoke VRPs. This is because;

- The TPP is not a part of the Bank Page flow to revocate VRP consents. See [here](https://standards.openbanking.org.uk/customer-experience-guidelines/pis-core-journeys/vrp/vrp-access-dashboard-revocation/v3-1-8/). Only the PSU and the AISP are involved in this journey. Therefore the TPP does not benefit from this UI.
- The TPP need to implement the flow that allows a PSU to revoke a VRP consent via the TPP app. The TPP only needs the OB VRP APIs necessary to obtain the data required to support this flow. We don't need to demonstrate an example TPP UI.

**Comment by BohoCode** [comment]
Generate VRP datamodels and controllers.

Using the latest swagger files, generate data classes (models) and controllers.
https://github.com/OpenBankingUK/read-write-api-specs/blob/v3.1.8r5/dist/openapi/vrp-openapi.yaml

**Comment by BohoCode** [comment]
Create VRP datamodel from 3.1.9r3 swagger definition. 

Jorge and I have reviewed the changes in the 3.1.9r3 VRP swagger spec, and there a no new objects or anything, just a much more complete model with enums defined and better sharing of classes rather than nesting. 

So, we think we will generate the data model from the 3.1.9r3 swagger spec and use that datamodel to implement the 3.1.8 controllers. This should make the move the 3.1.9 trivial too.

**Comment by BohoCode** [comment]
Closing. We now just need a solution for https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/50
