### ISSUE TITLE
AM Session Vulnerability (15 sept 2021)

### ISSUE THREAD

**Issue by jsanhc** [OpenBankingToolkit/openbanking-toolkit#40]
### Description
In all versions of AM there is a session hijacking vulnerability that allows anyone to take control of an active session in AM. This means any AM admin console or user session can be spoofed. 
### Reference
- [FR wiki: AM session vulnerability](https://wikis.forgerock.org/confluence/pages/viewpage.action?spaceKey=SA&title=15+Sept+2021+-+AM+Session+Vulnerability)
### Tasks
- [x] Apply the fix described in the FR wiki
- [x] Generate a new Open Banking AM war
- [x] Test the fix following the FR wiki

**Comment by jsanhc** [comment]
Builded a new AM war version:
- OpenAM-6.5.1-9f4e82458a.war
