### ISSUE TITLE
Implement Open Banking read/write apis v3.1.9

### ISSUE THREAD

**Issue by BohoCode** [OpenBankingToolkit/openbanking-toolkit#41]
## Description
Implement the [`Read/Write API` specification version v3.1.9](https://openbankinguk.github.io/read-write-api-site3/v3.1.9/profiles/read-write-data-api-profile.html)
- [Swagger spec v3.1.9r5](https://github.com/OpenBankingUK/read-write-api-specs/tree/v3.1.9r5/dist/openapi)
- Additional change log docs: https://openbanking.atlassian.net/wiki/spaces/WOR/pages/2331869354/252

## Tasks
- [x] Identify changes with respect to the version v3.1.8 to identify reusable classes
- [x] Model Class generation
- [x] Refactoring Model Class generation to use shared classes
- [x] Update uk-datamodel library development version to 3.1.9.0-SNAPSHOT
- [x] Controller Class generation
   - [x] OBVersion configuration
   - [x] Spring configuration api version
   - [x] Discovery api version
- [x] Bank UI app changes (if necessary)
- [x] Postman collection requests
- [x] Functional tests coverage
- [x] E2E UI tests

**Comment by jsanhc** [comment]
**Identify changes with respect to the version v3.1.8 to identify reusable classes**
- All the same with the below exceptions
   - VRP payments:
      - `OBDomesticVRPRequest` data/Risk isn't required in 3.1.9 (Remove Risk from Data in OBDomesticVRPRequest)
      - `OBDomesticVRPDetails` data/paymentTransactionId isn't required in 3.1.9 (Remove PaymentTransationId requirement in top level Data of OBDomesticVRPDetails)
      - Correct description override for PSUAuthenticationMethod

**Comment by jsanhc** [comment]
**Model Class generation**
It is not necessary to generate new model class generation for version 3.1.9 we can reuse the existing model classes.

**Comment by jsanhc** [comment]
Pending to close for the below reason:
- We need to think about how keep safe the certificates used for tests purposes.
- Fixed on https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/54
